name = "SbmlInterface"
uuid = "57fbc2bc-f8cb-4acb-844e-61ac977dec23"
authors = ["Paul F. Lang"]
version = "0.1.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
SymbolicUtils = "0.8"
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
